/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Logic.Service_Ventas;
import Model.*;
import Data_Gen.GenerateInfoFiles;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author serpe
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    private Service_Ventas servicio;
    private DefaultTableModel modeloTabla;


    /**
     * Creates new form MainFrame
     */
    public MainFrame() {

        servicio = new Service_Ventas();
        initComponents();
        modeloTabla = (DefaultTableModel) tablaVentas.getModel();
        setSize(1000, 600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        btnGenerarPrueba = new javax.swing.JButton();
        btnCargarArchivos = new javax.swing.JButton();
        btnCrearVendedor = new javax.swing.JButton();
        btnCrearProducto = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        panelCenter = new javax.swing.JPanel();
        panelFiltros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbFiltroVendedor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbFiltroProducto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        panelBottom = new javax.swing.JPanel();
        lblTotalGeneral = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión de Ventas");

        panelTop.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnGenerarPrueba.setBackground(new java.awt.Color(173, 216, 230));
        btnGenerarPrueba.setText("Generar Archivos Prueba");
        btnGenerarPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPruebaActionPerformed(evt);
            }
        });
        panelTop.add(btnGenerarPrueba);

        btnCargarArchivos.setText("Cargar Archivos");
        btnCargarArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivosActionPerformed(evt);
            }
        });
        panelTop.add(btnCargarArchivos);

        btnCrearVendedor.setText("Nuevo Vendedor");
        btnCrearVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearVendedorActionPerformed(evt);
            }
        });
        panelTop.add(btnCrearVendedor);

        btnCrearProducto.setText("Nuevo Producto");
        btnCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProductoActionPerformed(evt);
            }
        });
        panelTop.add(btnCrearProducto);

        btnExportar.setText("Exportar Datos");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        panelTop.add(btnExportar);

        getContentPane().add(panelTop, java.awt.BorderLayout.NORTH);

        panelCenter.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Filtrar por Vendedor:");
        panelFiltros.add(jLabel1);

        cmbFiltroVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        cmbFiltroVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFiltrosActionPerformed(evt);
            }
        });
        panelFiltros.add(cmbFiltroVendedor);

        jLabel2.setText(" | Filtrar por Producto:");
        panelFiltros.add(jLabel2);

        cmbFiltroProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        cmbFiltroProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFiltrosActionPerformed(evt);
            }
        });
        panelFiltros.add(cmbFiltroProducto);

        panelCenter.add(panelFiltros, java.awt.BorderLayout.NORTH);

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendedor", "Documento", "Producto", "Cantidad", "V. Unitario", "V. Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVentas);

        panelCenter.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelCenter, java.awt.BorderLayout.CENTER);

        lblTotalGeneral.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTotalGeneral.setText("Total Ventas: $0.00");
        panelBottom.add(lblTotalGeneral);

        getContentPane().add(panelBottom, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPruebaActionPerformed
        try {
            GenerateInfoFiles.generarArchivosPrueba();
            JOptionPane.showMessageDialog(this, "Archivos de prueba generados exitosamente.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerarPruebaActionPerformed

    private void btnCargarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivosActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(true);
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File[] files = fileChooser.getSelectedFiles();
            List<File> ventasFiles = new ArrayList<>();
            for (File file : files) 
            {
                try {
                    if (file.getName().equals("vendedores.csv")) servicio.procesarArchivoVendedores(file);
                    else if (file.getName().equals("productos.csv")) servicio.procesarArchivoProductos(file);
                    else if (file.getName().startsWith("vendedor_")) ventasFiles.add(file);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error cargando archivo maestro: " + file.getName());
                }
            }

            for (File file : ventasFiles) {
                try {
                    servicio.procesarArchivoVentas(file);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error cargando ventas: " + file.getName());
                }
            }
            actualizarComboVendedores();
            actualizarComboProductos();
            actualizarTabla();
        }
    }//GEN-LAST:event_btnCargarArchivosActionPerformed

    private void btnCrearVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearVendedorActionPerformed
        JTextField txtDoc = new JTextField(10); JTextField txtNombres = new JTextField(10); JTextField txtApellidos = new JTextField(10);
        JComboBox<String> cmbTipo = new JComboBox<>(new String[]{TipoDocumento.CC, TipoDocumento.CE, TipoDocumento.TI, TipoDocumento.NIT});
        JPanel panel = new JPanel(new GridLayout(4,2));
        panel.add(new JLabel("Tipo:")); panel.add(cmbTipo); panel.add(new JLabel("Doc:")); panel.add(txtDoc);
        panel.add(new JLabel("Nombres:")); panel.add(txtNombres); panel.add(new JLabel("Apellidos:")); panel.add(txtApellidos);
        
        if (JOptionPane.showConfirmDialog(this, panel, "Nuevo Vendedor", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            servicio.agregarVendedor(new Vendedor((String)cmbTipo.getSelectedItem(), txtDoc.getText(), txtNombres.getText(), txtApellidos.getText()));
            actualizarComboVendedores();
        }
    }//GEN-LAST:event_btnCrearVendedorActionPerformed

    private void btnCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProductoActionPerformed
        JTextField txtId = new JTextField(10); JTextField txtNombre = new JTextField(10); JTextField txtValor = new JTextField(10);
        JPanel panel = new JPanel(new GridLayout(3,2));
        panel.add(new JLabel("ID:")); panel.add(txtId); panel.add(new JLabel("Nombre:")); panel.add(txtNombre); panel.add(new JLabel("Valor:")); panel.add(txtValor);
        
        if (JOptionPane.showConfirmDialog(this, panel, "Nuevo Producto", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            try { servicio.agregarProducto(new Producto(txtId.getText(), txtNombre.getText(), Double.parseDouble(txtValor.getText()))); } 
            catch (NumberFormatException e) { JOptionPane.showMessageDialog(this, "Valor inválido."); }
            actualizarComboProductos();
        }
    }//GEN-LAST:event_btnCrearProductoActionPerformed

    private void cmbFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiltrosActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_cmbFiltrosActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        if (servicio.getVentas().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay ventas para exportar.");
            return;
        }
        String[] opciones = {"Por Vendedores", "Por Productos"};
        int seleccion = JOptionPane.showOptionDialog(this, "¿Qué tipo de reporte desea exportar?", 
                "Tipo de Exportación", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
                
        if (seleccion == -1) return; // Si el usuario cierra la ventana
        
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                String ruta = chooser.getSelectedFile().getAbsolutePath();
                if (seleccion == 0) {
                    servicio.exportarReporteVendedores(ruta);
                } else {
                    servicio.exportarReporteProductos(ruta);
                }
                JOptionPane.showMessageDialog(this, "Exportación generada exitosamente (CSV y JSON)");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error al exportar: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    private void cmbFiltroVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiltroVendedorActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_cmbFiltroVendedorActionPerformed

    private void actualizarComboVendedores() {
        String seleccionado = (String) cmbFiltroVendedor.getSelectedItem();
        cmbFiltroVendedor.removeAllItems();
        cmbFiltroVendedor.addItem("Todos");
        for (Vendedor v : servicio.getVendedores())
        {
            cmbFiltroVendedor.addItem(v.getDocumento() + " - " + v.getNombres());
        }
        if (seleccionado != null) cmbFiltroVendedor.setSelectedItem(seleccionado);
    }

    private void actualizarComboProductos()
    {
        String seleccionado = (String) cmbFiltroProducto.getSelectedItem();
        cmbFiltroProducto.removeAllItems();
        cmbFiltroProducto.addItem("Todos");
        for (Producto p : servicio.getProductos())
        {
            cmbFiltroProducto.addItem(p.getIdProducto() + " - " + p.getNombre());
        }
        if (seleccionado != null) cmbFiltroProducto.setSelectedItem(seleccionado);
    }

    private void actualizarTabla() {
        modeloTabla.setRowCount(0);
        double totalGeneral = 0;
        String fVendedor = (String) cmbFiltroVendedor.getSelectedItem();
        String fProducto = (String) cmbFiltroProducto.getSelectedItem();
        for (Venta v : servicio.getVentas())
        {
            String docStr = v.getVendedor().getDocumento() + " - " + v.getVendedor().getNombres();
            boolean matchVendedor = (fVendedor == null || fVendedor.equals("Todos") || fVendedor.equals(docStr));
            if (matchVendedor)
            {
                for (DetalleVenta dv : v.getDetalles())
                {
                    String prodStr = dv.getProducto().getIdProducto() + " - " + dv.getProducto().getNombre();
                    boolean matchProducto = (fProducto == null || fProducto.equals("Todos") || fProducto.equals(prodStr));
                    if (matchProducto)
                    {
                        Object[] fila = 
                        {
                            v.getVendedor().getNombres(), v.getVendedor().getDocumento(),
                            dv.getProducto().getNombre(), dv.getCantidad(),
                            String.format(java.util.Locale.US, "%.2f", dv.getValorUnitario()),
                            String.format(java.util.Locale.US, "%.2f", dv.getValorTotal())
                        };
                        modeloTabla.addRow(fila);
                        totalGeneral += dv.getValorTotal();
                    }
                }
            }
        }
        lblTotalGeneral.setText(String.format(java.util.Locale.US, "Total Filtrado: $%.2f", totalGeneral));
    }

        public static void iniciarInterfaz(String args[]) { 
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarArchivos;
    private javax.swing.JButton btnCrearProducto;
    private javax.swing.JButton btnCrearVendedor;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnGenerarPrueba;
    private javax.swing.JComboBox<String> cmbFiltroProducto;
    private javax.swing.JComboBox<String> cmbFiltroVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalGeneral;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JPanel panelTop;
    private javax.swing.JTable tablaVentas;
    // End of variables declaration//GEN-END:variables
}